// WIND APIs
//Determine district and add it to database
POST http://localhost:5000/winddata/save
Content-Type: application/json

{
   "district":"Newyork",
   "speed":"64",
   "sourceDirection":"North",
   "destinationDirection": "South",
   "date": "2022-10-20 14:30:00",
   "latitude":"67",
   "longitude":"90"
}


###

GET http://localhost:5000/winddata/getAllWindData

###

//timeStart and timeEnd are not handled right now
POST http://localhost:5000/winddata/AverageWindSpeed
Content-Type: application/json

{
   "district":"Thane",
   "sourceDirection":"south",
   "destinationDirection": "north",
   "timeStart": "2020-10-20 00:30:00",
   "timeEnd": "2020-10-20 19:30:00"
}
###
//Get probabaitly
POST http://localhost:5000/winddata/getProbability
Content-Type: application/json

{
   "sourceDirection": "north",
   "destinationDirection": "northwest"
}

###

//Get max wind and number of ocurrence
GET http://localhost:5000/winddata/getMaxWindSpeed

###

GET  http://localhost:5000/winddata/getWindDirectionOccurance

###

//Test Queries
GET http://localhost:5000/winddata/testQuery

###

//DISTRICT APIs

GET http://localhost:5000/districtdata/getAllDistrictData



###

GET http://localhost:5000/districtdata/getAllDistrictList

###

POST http://localhost:5000/districtdata/save
Content-Type: application/json

{
   "name":"Raigad",
   "coordinates":"12,34,54,32"
}
###

